# Generated by Django 5.2.13 on 2026-04-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["codigo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fecha", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("unidad", models.CharField(blank=True, max_length=40)),
                (
                    "responsable",
                    models.CharField(
                        choices=[("Supplier", "Supplier"), ("OEM", "OEM")],
                        max_length=20,
                    ),
                ),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[
                            ("1x1", "1x1"),
                            ("1xn", "1xn"),
                            ("nx1", "nx1"),
                            ("nxn", "nxn"),
                        ],
                        default="1x1",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="calibrations.feature",
                    ),
                ),
            ],
            options={
                "ordering": ["feature__codigo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CalibrationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.JSONField()),
                (
                    "status_madurez",
                    models.CharField(
                        choices=[
                            ("0.25", "0.25 - Inicial"),
                            ("0.5", "0.5 - Test bench"),
                            ("0.75", "0.75 - Vehicle"),
                            ("1.0", "1.0 - Homologation"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "verificacion",
                    models.CharField(
                        choices=[
                            ("No", "No"),
                            ("Test bench", "Test bench"),
                            ("Vehicle", "Vehicle"),
                            ("Homologation", "Homologation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_values",
                        to="calibrations.release",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_values",
                        to="calibrations.variable",
                    ),
                ),
            ],
            options={
                "ordering": ["release__fecha", "variable__nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="variable",
            constraint=models.UniqueConstraint(
                fields=("feature", "nombre"), name="unique_variable_nombre_per_feature"
            ),
        ),
        migrations.AddConstraint(
            model_name="calibrationvalue",
            constraint=models.UniqueConstraint(
                fields=("variable", "release"),
                name="unique_variable_release_calibration_value",
            ),
        ),
    ]
