# Generated by Django 5.2.13 on 2026-04-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='axis_x_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='variable',
            name='axis_x_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='axis_y_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='variable',
            name='axis_y_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='map_type',
            field=models.CharField(blank=True, choices=[('spark_advance', 'Spark Advance Map'), ('fuel_map', 'Fuel Map'), ('torque_map', 'Torque Map'), ('generic', 'Generic Map'), ('', 'Scalar / No map')], default='', max_length=30),
        ),
    ]
