# Generated by Django 5.2.10 on 2026-02-05 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Imagen principal del artículo', null=True, upload_to='articles/%Y/%m/', verbose_name='Imagen destacada'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(help_text='Resumen breve del artículo', max_length=500, verbose_name='Extracto'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verificado por profesional', verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, help_text='Fuente de referencia', null=True, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.tag', verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas'),
        ),
    ]
