# Generated by Django 5.2.13 on 2026-04-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de release"
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
            ],
            options={
                "verbose_name": "Release",
                "verbose_name_plural": "Releases",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="Unidad"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variables",
                        to="calibration.feature",
                        verbose_name="Feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable",
                "verbose_name_plural": "Variables",
                "ordering": ["feature", "name"],
            },
        ),
        migrations.CreateModel(
            name="CalibrationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, max_digits=20, verbose_name="Valor"
                    ),
                ),
                (
                    "maturity",
                    models.CharField(
                        choices=[
                            ("0.25", "25 % – Inicial"),
                            ("0.50", "50 % – En desarrollo"),
                            ("0.75", "75 % – Avanzado"),
                            ("1.00", "100 % – Final"),
                        ],
                        default="0.25",
                        max_length=4,
                        verbose_name="Madurez",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "responsible",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Responsable"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calibration_values",
                        to="calibration.release",
                        verbose_name="Release",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calibration_values",
                        to="calibration.variable",
                        verbose_name="Variable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de calibración",
                "verbose_name_plural": "Valores de calibración",
                "ordering": ["release", "variable"],
                "unique_together": {("variable", "release")},
            },
        ),
    ]
